# This is a configuration file for pytest, a testing framework for Python.
#addopts: Defines extra parameters that are automatically added every time you run a test.

#--alluredir=allure-results: Ensures your test report data is always saved into the allure-results folder automatically.

#-v (Verbose): Shows detailed test function names and their statuses clearly in the terminal.
[pytest]
addopts = --alluredir=allure-results -v

